insert into public.companies (
  slug,
  name,
  website,
  short_description,
  category,
  location_label,
  city,
  latitude,
  longitude,
  founded,
  logo_url,
  map_sprite,
  source_url
)
values
  (
    'openai',
    'OpenAI',
    'https://openai.com',
    'Frontier AI lab behind ChatGPT and a huge share of the current AI wave.',
    'Core Labs',
    '1455 3rd St, San Francisco',
    'sf',
    37.7700459,
    -122.3887896,
    2015,
    null,
    'default',
    'https://cdn.openai.com/pdf/8e938d69-0b67-4994-b9ff-683733ed587e/openai-letter-minister-solomon.pdf'
  ),
  (
    'anthropic',
    'Anthropic',
    'https://www.anthropic.com',
    'Claude-maker focused on frontier models, safety, and serious product adoption.',
    'Core Labs',
    '500 Howard St, San Francisco',
    'sf',
    37.7884892,
    -122.3967349,
    2021,
    null,
    'default',
    'https://www.bizprofile.net/ca/san-francisco/anthropic-inc'
  ),
  (
    'perplexity',
    'Perplexity',
    'https://www.perplexity.ai',
    'Answer engine with a strong consumer feel and nonstop mindshare.',
    'Consumer AI',
    '115 Sansome St, San Francisco',
    'sf',
    37.7914533,
    -122.4010654,
    2022,
    null,
    'default',
    'https://craft.co/perplexity-ai/locations'
  ),
  (
    'scale-ai',
    'Scale AI',
    'https://scale.com',
    'Data, evaluation, and enterprise infrastructure for training and deploying AI.',
    'Infra',
    '650 Townsend St, San Francisco',
    'sf',
    37.7709567,
    -122.4036566,
    2016,
    null,
    'default',
    'https://craft.co/scale-ai/locations'
  ),
  (
    'baseten',
    'Baseten',
    'https://www.baseten.com',
    'Inference platform for shipping AI products fast with production-ready performance.',
    'Infra',
    '575 Sutter St, San Francisco',
    'sf',
    37.7888158,
    -122.4097317,
    2019,
    null,
    'default',
    'https://craft.co/baseten/locations'
  ),
  (
    'fin',
    'Fin',
    'https://fin.ai',
    'Fin is an AI Agent system for customer service: a fully configurable AI-powered customer agent that resolves complex support, success, and sales queries.',
    'Vertical AI',
    '55 Second St, San Francisco',
    'sf',
    37.78882824961475,
    -122.40029289081181,
    2011,
    null,
    'default',
    'https://www.intercom.com/about'
  ),
  (
    'harvey',
    'Harvey',
    'https://www.harvey.ai',
    'Legal AI company building one of the clearest vertical AI success stories.',
    'Vertical AI',
    '575 Market St, San Francisco',
    'sf',
    37.7895414,
    -122.4003752,
    2022,
    null,
    'default',
    'https://craft.co/harvey-ai/locations'
  ),
  (
    'xai',
    'xAI',
    'https://x.ai',
    'Elon Musk''s AI lab building Grok, focused on reasoning and truth-seeking.',
    'Core Labs',
    '3180 18th St, San Francisco',
    'sf',
    37.7622,
    -122.4146,
    2023,
    null,
    'default',
    'https://traded.co/deals/california/office/lease/3180-18th-street/'
  ),
  (
    'sierra',
    'Sierra',
    'https://sierra.ai',
    'AI agents for enterprise customer experience, co-founded by Bret Taylor and Clay Bavor.',
    'Agents',
    '235 Second St, San Francisco',
    'sf',
    37.786,
    -122.3972,
    2023,
    null,
    'default',
    'https://traded.co/deals/california/office/lease/235-second-street/'
  ),
  (
    'thinking-machines',
    'Thinking Machines Lab',
    'https://thinkingmachines.ai',
    'AI research lab co-founded by former OpenAI CTO Mira Murati, building frontier AI models.',
    'Core Labs',
    '2300 Harrison St, San Francisco',
    'sf',
    37.7606,
    -122.4127,
    2025,
    null,
    'default',
    'https://traded.co/deals/california/office/lease/2300-harrison-street/'
  ),
  (
    'together-ai',
    'Together AI',
    'https://www.together.ai',
    'Cloud platform for running and fine-tuning open-source AI models at scale.',
    'Infra',
    '251 Rhode Island St, San Francisco',
    'sf',
    37.7667,
    -122.4027,
    2022,
    null,
    'default',
    'https://www.together.ai/terms-of-service'
  ),
  (
    'cursor',
    'Cursor',
    'https://cursor.com',
    'AI-powered code editor built on VS Code with deep LLM integration for code generation.',
    'Devtools',
    '33 New Montgomery St, San Francisco',
    'sf',
    37.7886,
    -122.4013,
    2022,
    null,
    'default',
    'https://www.cbinsights.com/company/anysphere'
  ),
  (
    'delphi',
    'Delphi',
    'https://www.delphi.ai',
    'Builds conversational digital twins for experts and creators—on-brand, always-on stand-ins that answer fans and clients in their voice.',
    'Consumer AI',
    '850 Montgomery St, Suite 350, San Francisco',
    'sf',
    37.7969892,
    -122.4035081,
    2022,
    null,
    'default',
    'https://www.delphi.ai/terms-of-use'
  ),
  (
    'cognition',
    'Cognition',
    'https://cognition.ai',
    'Creator of Devin, an autonomous AI software engineer for end-to-end coding tasks.',
    'Agents',
    '1875 Mission St, San Francisco',
    'sf',
    37.7671,
    -122.4198,
    2023,
    null,
    'default',
    'https://www.bizprofile.net/ca/san-francisco/cognition-ai-inc'
  ),
  (
    'physical-intelligence',
    'Physical Intelligence',
    'https://physicalintelligence.company',
    'AI research lab building general-purpose foundation models for robotics.',
    'Core Labs',
    '396 Treat Ave, San Francisco',
    'sf',
    37.7639,
    -122.4136,
    2024,
    null,
    'default',
    'https://www.bizprofile.net/ca/san-francisco/physical-intelligence-pi-inc'
  ),
  (
    'cohere',
    'Cohere',
    'https://cohere.com',
    'Enterprise AI platform building large language models for business applications.',
    'Core Labs',
    '755 Sansome St, San Francisco',
    'sf',
    37.7972,
    -122.402,
    2019,
    null,
    'default',
    'https://bandana.com/companies/e362a6da-588c-42f7-bd1a-538c52757bb7/locations/418a9ab4-a428-4a8b-94b6-2d78bbbcaf0f'
  ),
  (
    'elevenlabs',
    'ElevenLabs',
    'https://elevenlabs.io',
    'AI voice technology platform for realistic speech synthesis and voice cloning.',
    'Infra',
    '303 2nd St, San Francisco',
    'sf',
    37.7849,
    -122.3958,
    2022,
    null,
    'default',
    'https://websets.exa.ai/websets/directory/elevenlabs-offices'
  ),
  (
    'writer',
    'Writer',
    'https://writer.com',
    'Enterprise AI platform for building and deploying AI agents grounded in company data.',
    'Vertical AI',
    '111 Maiden Lane, San Francisco',
    'sf',
    37.788,
    -122.4062,
    2020,
    null,
    'default',
    'https://www.cbinsights.com/company/qordoba'
  ),
  (
    '11x',
    '11x',
    'https://www.11x.ai',
    'AI digital workers that automate sales development and go-to-market tasks.',
    'Agents',
    '677 Harrison St, San Francisco',
    'sf',
    37.7829,
    -122.3969,
    2022,
    null,
    'default',
    'https://www.bizprofile.net/ca/san-francisco/11x-ai-inc'
  ),
  (
    'abnormal',
    'Abnormal Security',
    'https://abnormal.ai',
    'AI-powered email security platform that detects and prevents business email compromise.',
    'Vertical AI',
    '185 Clara St, San Francisco',
    'sf',
    37.7799,
    -122.4017,
    2018,
    null,
    'default',
    'https://opengovus.com/sam-entity/C1MPKNUNE761'
  ),
  (
    'imbue',
    'Imbue',
    'https://imbue.com',
    'AI research lab building agents that can reason and code, formerly Generally Intelligent.',
    'Core Labs',
    '2261 Market St, San Francisco',
    'sf',
    37.7647,
    -122.4322,
    2021,
    null,
    'default',
    'https://files.nitrd.gov/90-fr-9088/Imbue-AI-RFI-2025.pdf'
  ),
  (
    'llamaindex',
    'LlamaIndex',
    'https://www.llamaindex.ai',
    'Open-source data framework for connecting custom data sources with LLMs.',
    'Devtools',
    '325 5th St, San Francisco',
    'sf',
    37.7801,
    -122.4031,
    2022,
    null,
    'default',
    'https://www.builtinsf.com/company/llamaindex'
  ),
  (
    'langchain',
    'LangChain',
    'https://www.langchain.com',
    'Open-source framework and platform for building LLM-powered applications.',
    'Devtools',
    '42 Decatur St, San Francisco',
    'sf',
    37.7726,
    -122.4063,
    2023,
    null,
    'default',
    'https://www.bizprofile.net/ca/san-francisco/langchain-inc'
  ),
  (
    'wandb',
    'Weights & Biases',
    'https://wandb.ai',
    'ML developer platform for experiment tracking, model management, and dataset versioning.',
    'Infra',
    '400 Alabama St, San Francisco',
    'sf',
    37.7641,
    -122.4124,
    2017,
    null,
    'default',
    'https://www.bizprofile.net/ca/san-francisco/weights-and-biases-inc'
  ),
  (
    'descript',
    'Descript',
    'https://www.descript.com',
    'AI-powered video and podcast editor enabling text-based media editing.',
    'Consumer AI',
    '375 Alabama St, San Francisco',
    'sf',
    37.7645,
    -122.4123,
    2017,
    null,
    'default',
    'https://www.descript.com/terms'
  ),
  (
    'lightfield',
    'Lightfield',
    'https://lightfield.app',
    'AI-native CRM built by the team behind Tome, the AI presentation tool.',
    'Vertical AI',
    '600 Townsend St, San Francisco',
    'sf',
    37.7718,
    -122.4018,
    2020,
    null,
    'default',
    'https://www.cbinsights.com/company/tome-1'
  ),
  (
    'browserbase',
    'Browserbase',
    'https://www.browserbase.com',
    'Cloud platform providing headless browser infrastructure for AI agents.',
    'Infra',
    '166 Geary St, San Francisco',
    'sf',
    37.7877,
    -122.406,
    2024,
    null,
    'default',
    'https://www.bizprofile.net/ca/san-francisco/browserbase-inc'
  ),
  (
    'labelbox',
    'Labelbox',
    'https://labelbox.com',
    'AI data platform for training data labeling, curation, and model evaluation.',
    'Infra',
    '510 Treat Ave, San Francisco',
    'sf',
    37.762,
    -122.4145,
    2018,
    null,
    'default',
    'https://www.zoominfo.com/c/labelbox-inc/452502399'
  ),
  (
    'fal',
    'fal',
    'https://fal.ai',
    'The world''s best generative image, video, and audio models, all in one place. Develop and fine-tune models with serverless GPUs and on-demand clusters.',
    'Infra',
    '128 Spear St, San Francisco',
    'sf',
    37.79205667671866,
    -122.3936304729652,
    2021,
    'https://fal.ai/fal-icon.svg',
    'default',
    'https://fal.ai/'
  ),
  (
    'forethought',
    'Forethought',
    'https://forethought.ai',
    'AI agents platform automating customer support ticket resolution for enterprises.',
    'Agents',
    '345 California St, San Francisco',
    'sf',
    37.7931,
    -122.4005,
    2017,
    null,
    'default',
    'https://www.cbinsights.com/company/forethought-technologies'
  ),
  (
    'sourcegraph',
    'Sourcegraph',
    'https://sourcegraph.com',
    'Code intelligence platform with AI-powered search and the Amp coding agent.',
    'Devtools',
    '400 Montgomery St, San Francisco',
    'sf',
    37.7929,
    -122.4027,
    2013,
    null,
    'default',
    'https://github.com/sourcegraph/handbook/blob/main/content/company-info-and-process/about-sourcegraph/general-office-info.md'
  ),
  (
    'wispr',
    'Wispr Flow',
    'https://wisprflow.ai',
    'AI voice dictation app that adapts to each user''s writing style.',
    'Consumer AI',
    '444 Townsend St, San Francisco',
    'sf',
    37.7746,
    -122.3983,
    2021,
    null,
    'default',
    'https://www.cbinsights.com/company/wispr'
  ),
  (
    'bland',
    'Bland AI',
    'https://www.bland.ai',
    'Enterprise platform for AI phone agents handling sales, support, and scheduling.',
    'Agents',
    '292 Ivy St, San Francisco',
    'sf',
    37.7774,
    -122.4229,
    2023,
    null,
    'default',
    'https://craft.co/bland-ai/locations'
  ),
  (
    'databricks',
    'Databricks',
    'https://www.databricks.com',
    'Unified data and AI platform combining data warehousing, engineering, and ML at scale.',
    'Infra',
    '160 Spear St, San Francisco',
    'sf',
    37.7912,
    -122.3936,
    2013,
    null,
    'default',
    'https://www.databricks.com/company/contact/office-locations'
  ),
  (
    'glean',
    'Glean',
    'https://www.glean.com',
    'AI-powered enterprise search platform connecting all company data for instant answers.',
    'Vertical AI',
    '255 California St, San Francisco',
    'sf',
    37.7932,
    -122.3997,
    2019,
    null,
    'default',
    'https://salestools.io/en/report/glean-headquarters'
  ),
  (
    'mercor',
    'Mercor',
    'https://www.mercor.com',
    'AI-powered hiring platform that matches talent to jobs using AI interviews and evaluation.',
    'Vertical AI',
    '181 Fremont St, San Francisco',
    'sf',
    37.7901,
    -122.3953,
    2023,
    null,
    'default',
    'https://www.builtinsf.com/company/mercor'
  ),
  (
    'luma',
    'Luma AI',
    'https://lumalabs.ai',
    'AI platform for 3D and video generation, creators of Dream Machine.',
    'Consumer AI',
    '457 Bryant St, San Francisco',
    'sf',
    37.7823,
    -122.3969,
    2021,
    null,
    'default',
    'https://talent.amplifypartners.com/jobs/luma-ai'
  ),
  (
    'magic',
    'Magic',
    'https://magic.dev',
    'AI coding company building frontier models with long context for software development.',
    'Devtools',
    '580 California St, San Francisco',
    'sf',
    37.7926,
    -122.4044,
    2022,
    null,
    'default',
    'https://exa.ai/websets/directory/magic-ai-offices'
  ),
  (
    'hebbia',
    'Hebbia',
    'https://www.hebbia.com',
    'AI platform for knowledge work that reasons across millions of documents for finance and law.',
    'Vertical AI',
    '575 Market St, San Francisco',
    'sf',
    37.7893,
    -122.4005,
    2020,
    null,
    'default',
    'https://www.hebbia.com/newsroom/hebbia-opens-doors-in-san-francisco-and-welcomes-new-cto'
  ),
  (
    'replicate',
    'Replicate',
    'https://replicate.com',
    'Cloud API for running open-source ML models with simple deployment.',
    'Infra',
    '2261 Market St, San Francisco',
    'sf',
    37.765,
    -122.4318,
    2019,
    null,
    'default',
    'https://replicate.com/privacy'
  ),
  (
    'modal',
    'Modal',
    'https://modal.com',
    'Serverless cloud platform for running AI and data workloads on GPUs.',
    'Infra',
    '375 Alabama St, San Francisco',
    'sf',
    37.7651442,
    -122.4143487,
    2021,
    null,
    'default',
    'https://github.com/taishikato/sf-ai-startup-quest/issues/16'
  ),
  (
    'chroma',
    'Chroma',
    'https://www.trychroma.com',
    'Open-source vector database for building AI applications with embeddings.',
    'Infra',
    '2261 Market St, San Francisco',
    'sf',
    37.7644,
    -122.432,
    2022,
    null,
    'default',
    'https://opengovus.com/san-francisco-business/1304237-05-221'
  ),
  (
    'jasper',
    'Jasper',
    'https://www.jasper.ai',
    'AI content generation platform for marketing teams and enterprises.',
    'Consumer AI',
    '575 Market St, San Francisco',
    'sf',
    37.7897,
    -122.4001,
    2021,
    null,
    'default',
    'https://www.jasper.ai/legal/terms'
  ),
  (
    'cresta',
    'Cresta',
    'https://cresta.com',
    'Real-time AI platform for contact centers providing agent assist and coaching.',
    'Agents',
    '235 Pine St, San Francisco',
    'sf',
    37.7922,
    -122.3998,
    2017,
    null,
    'default',
    'https://salestools.io/en/report/cresta-headquarters'
  ),
  (
    'primer',
    'Primer',
    'https://primer.ai',
    'AI platform automating intelligence analysis and report generation for defense and security.',
    'Vertical AI',
    '244 Jackson St, San Francisco',
    'sf',
    37.7969,
    -122.3999,
    2015,
    null,
    'default',
    'https://craft.co/primer-ai/locations'
  ),
  (
    'abridge',
    'Abridge',
    'https://www.abridge.com',
    'Generative AI platform for clinical documentation used by 150+ health systems.',
    'Vertical AI',
    '208 Utah St, San Francisco',
    'sf',
    37.7632,
    -122.4043,
    2018,
    null,
    'default',
    'https://sfstandard.com/2025/10/07/abridge-ai-san-francisco-office-leasing/'
  ),
  (
    'distyl',
    'Distyl AI',
    'https://distyl.ai',
    'Enterprise AI orchestration platform rebuilding business processes with autonomous agents.',
    'Agents',
    '55 Hawthorne St, San Francisco',
    'sf',
    37.7862,
    -122.3985,
    2022,
    null,
    'default',
    'https://www.builtinsf.com/company/distyl-ai'
  ),
  (
    'nightfall',
    'Nightfall AI',
    'https://www.nightfall.ai',
    'AI-native data loss prevention platform protecting sensitive data across cloud apps.',
    'Vertical AI',
    '425 California St, San Francisco',
    'sf',
    37.7929,
    -122.4018,
    2019,
    null,
    'default',
    'https://www.cbinsights.com/company/nightfall-ai'
  ),
  (
    'adept',
    'Adept AI',
    'https://www.adept.ai',
    'AI research lab building agents that take actions in software for users.',
    'Agents',
    '350 Rhode Island St, San Francisco',
    'sf',
    37.766,
    -122.4031,
    2022,
    null,
    'default',
    'https://therealdeal.com/san-francisco/2023/08/10/adept-ai-labs-to-lease-35k-sf-in-san-franciscos-area-ai/'
  ),
  (
    'deepgram',
    'Deepgram',
    'https://deepgram.com',
    'Speech AI platform providing fast, accurate transcription and speech understanding APIs.',
    'Infra',
    '548 Market St, San Francisco',
    'sf',
    37.7899,
    -122.3998,
    2015,
    null,
    'default',
    'https://craft.co/deepgram/locations'
  ),
  (
    'woebot',
    'Woebot Health',
    'https://woebothealth.com',
    'AI-powered mental health platform delivering evidence-based therapy at scale.',
    'Vertical AI',
    '650 5th St, San Francisco',
    'sf',
    37.7759,
    -122.3972,
    2017,
    null,
    'default',
    'https://www.bbb.org/us/ca/san-francisco/profile/lab/woebot-labs-inc-1116-889119'
  ),
  (
    'rad-ai',
    'Rad AI',
    'https://www.radai.com',
    'Generative AI models trained specifically for radiology to automate clinical reporting.',
    'Vertical AI',
    '548 Market St, San Francisco',
    'sf',
    37.7903,
    -122.4003,
    2018,
    null,
    'default',
    'https://www.cbinsights.com/company/rad-ai'
  ),
  (
    'assemblyai',
    'AssemblyAI',
    'https://www.assemblyai.com',
    'AI platform for speech recognition, speaker detection, and audio intelligence APIs.',
    'Infra',
    '320 Judah St, San Francisco',
    'sf',
    37.7612,
    -122.4606,
    2017,
    null,
    'default',
    'https://www.cbinsights.com/company/assemblyai'
  ),
  (
    'tusk',
    'Tusk',
    'https://www.usetusk.ai',
    'AI testing platform that automates unit and integration testing using live traffic',
    'Devtools',
    '1885 Mission St, San Francisco',
    'sf',
    37.766922,
    -122.419655,
    2024,
    null,
    'default',
    'https://www.usetusk.ai'
  ),
  (
    'capy',
    'Capy',
    'https://capy.ai',
    'Coding platform that orchestrates autonomous cloud agents in parallel, shipping entire development sprints from a single dashboard.',
    'Devtools',
    '495 3rd St, San Francisco',
    'sf',
    37.781653,
    -122.3958575,
    2024,
    null,
    'default',
    'https://capy.ai'
  ),
  (
    'composite',
    'Composite',
    'https://composite.com',
    'Browser automation agent that predicts and executes your next action, doing work on your behalf.',
    'Agents',
    '425 2nd St, San Francisco',
    'sf',
    37.7846,
    -122.3942,
    2024,
    null,
    'default',
    'https://composite.com'
  ),
  (
    'y-combinator',
    'Y Combinator',
    'https://www.ycombinator.com',
    'The accelerator that shaped modern startup culture — the final boss of the Bay Area map.',
    'Infra',
    '335 Pioneer Way, Mountain View',
    'sf',
    37.3862565,
    -122.0668804,
    2005,
    'https://www.google.com/s2/favicons?domain=ycombinator.com&sz=128',
    'boss',
    'https://www.openstreetmap.org/search?query=335%20Pioneer%20Way%20Mountain%20View%20CA'
  ),
  (
    'circleback',
    'Circleback',
    'https://circleback.ai',
    'AI-powered notes, action items, automations, and search.',
    'Consumer AI',
    '100 Green St, San Francisco',
    'sf',
    37.800521,
    -122.401598,
    2023,
    null,
    'default',
    'https://circleback.ai'
  ),
  (
    'reevo',
    'Reevo',
    'https://reevo.ai',
    'AI revenue operating system that unifies lead gen, outreach, call intelligence, and CRM in one GTM platform.',
    'Vertical AI',
    '2 Embarcadero Center, San Francisco',
    'sf',
    37.7947881,
    -122.3984101,
    2024,
    'https://reevo.ai/assets/images/favicon-light.png',
    'default',
    'https://www.wework.com/buildings/2-embarcadero-center--san-francisco--CA'
  ),
  (
    'gauge',
    'Gauge',
    'https://withgauge.com',
    'AI-powered platform that monitors and optimizes brand visibility across generative search engines like ChatGPT, Gemini, and Perplexity.',
    'Vertical AI',
    '11 Funston Ave, San Francisco',
    'sf',
    37.7865235,
    -122.4723023,
    2024,
    null,
    'default',
    'https://withgauge.com'
  )
on conflict (city, slug) do update
set
  name = excluded.name,
  website = excluded.website,
  short_description = excluded.short_description,
  category = excluded.category,
  location_label = excluded.location_label,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  founded = excluded.founded,
  logo_url = excluded.logo_url,
  map_sprite = excluded.map_sprite,
  source_url = excluded.source_url;
