insert into public.companies (
  slug,
  name,
  website,
  short_description,
  category,
  location_label,
  city,
  latitude,
  longitude,
  founded,
  logo_url,
  map_sprite,
  source_url
)
values
  (
    'adclear',
    'Adclear',
    'https://www.adclear.ai/',
    'AI compliance platform for reviewing financial promotions and marketing copy faster.',
    'Vertical AI',
    '85 Great Portland St, London W1W 7LT',
    'london',
    51.51857139472014,
    -0.14248638858861662,
    2024,
    null,
    'default',
    'https://www.startupmap.london/companies/adclear'
  ),
  (
    'fyxer-ai',
    'Fyxer AI',
    'https://www.fyxer.com/',
    'AI executive assistant for inbox triage, meeting prep, and follow-up workflows.',
    'Agents',
    '53-64 Chancery Ln, London WC2A 1QS',
    'london',
    51.516214,
    -0.112095,
    2023,
    null,
    'default',
    'https://www.startupmap.london/companies/fyxer-ai'
  ),
  (
    'metris',
    'Metris',
    'https://www.metrisenergy.com/',
    'AI energy operations platform for monitoring solar assets and predicting faults.',
    'Vertical AI',
    '7 Bell Yard, London WC2A 2JR',
    'london',
    51.51440031,
    -0.11176773154265628,
    2023,
    null,
    'default',
    'https://www.startupmap.london/companies/metris'
  ),
  (
    'compass-labs',
    'Compass Labs',
    'https://www.compasslabs.ai/',
    'Simulation platform for testing DeFi protocols and risk scenarios before deployment.',
    'Vertical AI',
    'Kemp House, 128 City Rd, London EC1V 2NX',
    'london',
    51.52721032,
    -0.0888977162,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/compass-labs'
  ),
  (
    'paracosmic',
    'Paracosmic',
    'https://paracosmic.com/',
    'Generative world-building platform for creating interactive game environments from prompts.',
    'Consumer AI',
    '529 Kingsland Road, Dalston, London, E8 4AR',
    'london',
    51.54586724,
    -0.07599287571830167,
    2019,
    null,
    'default',
    'https://www.startupmap.london/companies/paracosmic'
  ),
  (
    'asteroid-ai',
    'Asteroid.ai',
    'https://asteroid.ai/',
    'Runtime supervision layer for monitoring and constraining AI agent behavior in production.',
    'Infra',
    'EC1N 8TS, London',
    'london',
    51.52008363502,
    -0.1064415496,
    2024,
    null,
    'default',
    'https://www.startupmap.london/companies/asteroid-ai'
  ),
  (
    'arda-biomaterials',
    'Arda Biomaterials',
    'https://arda.bio/',
    'AI-enabled materials company turning waste feedstocks into next-generation biomaterials.',
    'Vertical AI',
    '74 Gedling Pl, London SE1 2JS',
    'london',
    51.49849214,
    -0.07402407387,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/arda-biomaterials'
  ),
  (
    'recurse-ml',
    'RecurseML',
    'https://www.recurse.ml/',
    'ML developer tooling for testing, benchmarking, and safeguarding models in CI pipelines.',
    'Devtools',
    '64 Nile Street, London N1 7SR',
    'london',
    51.52937969,
    -0.08824992969,
    2023,
    null,
    'default',
    'https://www.startupmap.london/companies/recurse-ml'
  ),
  (
    'synthera-ai',
    'Synthera AI',
    'https://www.synthera.ai/',
    'Generative market simulation company building proprietary models for portfolio analysis.',
    'Core Labs',
    'Canvas, 321 Oxford Street, London W1C 2HX',
    'london',
    51.51462619,
    -0.1460846738,
    2024,
    null,
    'default',
    'https://www.startupmap.london/companies/synthera-ai'
  ),
  (
    'helmguard-ai',
    'HelmGuard AI',
    'https://helmguard.ai/',
    'Cybersecurity platform built to monitor and defend AI systems and workflows.',
    'Infra',
    'Shoreditch Exchange, Gorsuch Pl, London E2 8JF',
    'london',
    51.53020744,
    -0.07489480511,
    2024,
    null,
    'default',
    'https://www.startupmap.london/companies/helmguard-ai'
  ),
  (
    'genie-fertility',
    'Genie Fertility',
    'https://geniefertility.com/',
    'AI fertility diagnostics company helping clinics tailor IVF protocols and implantation planning.',
    'Vertical AI',
    '192 Drummond Street, Fourth Floor, London NW1 3HP',
    'london',
    51.52265909736302,
    -0.1139158975,
    2024,
    null,
    'default',
    'https://www.startupmap.london/companies/genie-fertility'
  ),
  (
    'wilsonai',
    'WilsonAI',
    'https://www.getwilson.ai/',
    'Legal operations copilot for triaging requests and automating internal legal workflows.',
    'Agents',
    '24 Southwark Bridge Road, London, England, SE1 9HF',
    'london',
    51.50632376,
    -0.09327031489,
    2024,
    null,
    'default',
    'https://find-and-update.company-information.service.gov.uk/company/15894184'
  ),
  (
    'assuric',
    'Assuric',
    'https://www.assuric.com/',
    'AI compliance software for medical device teams managing regulatory submissions.',
    'Vertical AI',
    '20 Wenlock Road, London, United Kingdom, N1 7GU',
    'london',
    51.53070578,
    -0.09360860086,
    2024,
    null,
    'default',
    'https://find-and-update.company-information.service.gov.uk/company/15655052'
  ),
  (
    'neurosonic',
    'NeuroSonic',
    'https://www.neuro-sonic.com/',
    'Neurovascular assessment company using AI to surface stroke risk insights from scans.',
    'Vertical AI',
    'Flat 3 13 Fortis Green Avenue, London N2 9LY',
    'london',
    51.59045409,
    -0.1537409892,
    2010,
    null,
    'default',
    'https://www.startupmap.london/companies/neurosonic'
  ),
  (
    'phycobloom',
    'Phycobloom',
    'https://www.phycobloom.com/',
    'AI and bioengineering startup optimizing microalgae for low-carbon fuel production.',
    'Vertical AI',
    'Unit 130 Westbourne Studios, 242 Acklam Road, London W10 5JJ',
    'london',
    51.52143163,
    -0.2028238683,
    2019,
    null,
    'default',
    'https://www.startupmap.london/companies/phycobloom'
  ),
  (
    'tonk-labs',
    'Tonk Labs',
    'https://tonk.xyz/',
    'Code-first AI tooling for generating dashboards, agents, and apps from mixed inputs.',
    'Devtools',
    '64 Nile Street, London, England, N1 7SR',
    'london',
    51.52934631,
    -0.08827138736,
    2023,
    null,
    'default',
    'https://www.startupmap.london/companies/tonk-labs'
  ),
  (
    'ulyssean',
    'Ulyssean',
    'https://ulyssean.com/',
    'Infrastructure startup building software and hardware for AI data center operations.',
    'Infra',
    'Senna Building, Shoreditch Exchange, Gorsuch Place, London E2 8JF',
    'london',
    51.53022443945398,
    -0.07598400215160428,
    2025,
    null,
    'default',
    'https://www.startupmap.london/companies/ulyssean'
  ),
  (
    'delfa',
    'Delfa',
    'https://www.delfa.ai/',
    'Clinical trial operations agents for recruitment, screening, and follow-up workflows.',
    'Agents',
    '20-22 Wenlock Road, London N1 7GU',
    'london',
    51.530774784578064,
    -0.09356443154172409,
    2025,
    null,
    'default',
    'https://www.startupmap.london/companies/delfa'
  ),
  (
    'metavoice-io',
    'MetaVoice',
    'https://www.metavoice.io/',
    'Voice model company building duplex speech-to-speech systems for natural conversations.',
    'Core Labs',
    '30 Moorgate, London EC2R 6PJ',
    'london',
    51.5166103168409,
    -0.0888768243293369,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/metavoice-io'
  ),
  (
    'plumerai',
    'Plumerai',
    'https://plumerai.com/',
    'Edge AI infrastructure for compressing and deploying deep learning on low-power chips.',
    'Infra',
    'Uncommon, 1 Long Lane, London SE1 4PG',
    'london',
    51.50123089313549,
    -0.0918756338479948,
    2017,
    null,
    'default',
    'https://www.startupmap.london/companies/plumerai'
  ),
  (
    'tortus-ai',
    'Tortus AI',
    'https://tortus.ai/',
    'Clinical documentation copilot for automating note-taking, coding, and billing in EHRs.',
    'Agents',
    '193-197 High Holborn, London WC1V 7BD',
    'london',
    51.517161280674664,
    -0.122560302707005,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/tortus-ai'
  ),
  (
    'trace',
    'Tracelight',
    'https://tracelight.ai/',
    'Spreadsheet-native AI for forecasting, scenario analysis, and finance data cleanup.',
    'Agents',
    'Senna Building, Gorsuch Place, London E2 8JF',
    'london',
    51.530234764996464,
    -0.07545314549325922,
    2024,
    null,
    'default',
    'https://www.startupmap.london/companies/trace'
  ),
  (
    'nodes-links',
    'Nodes & Links',
    'https://nodeslinks.com/',
    'Knowledge graph platform for surfacing project schedule risk across construction programs.',
    'Vertical AI',
    '107 Fleet Street, London EC4A 2AB',
    'london',
    51.51439806257906,
    -0.10484752969422052,
    2018,
    null,
    'default',
    'https://www.startupmap.london/companies/nodes-links'
  ),
  (
    'mitra-bio',
    'Mitra Bio',
    'https://mitrabio.tech/',
    'AI biology platform for evaluating dermatology compounds from molecular skin data.',
    'Vertical AI',
    '84 Wood Lane, London W12 0BZ',
    'london',
    51.51592430865977,
    -0.2244334162005999,
    2020,
    null,
    'default',
    'https://www.startupmap.london/companies/mitra-bio'
  ),
  (
    'ameba',
    'Ameba',
    'https://www.ameba.ai/',
    'Supply chain intelligence platform using AI to monitor status, disruptions, and quality risk.',
    'Vertical AI',
    '116 Commercial Street, London E1 6NF',
    'london',
    51.5206159060686,
    -0.07440020270679744,
    2023,
    null,
    'default',
    'https://www.startupmap.london/companies/ameba'
  ),
  (
    'micrographia-bio',
    'Micrographia Bio',
    'https://www.micrographiabio.com/',
    'AI drug discovery company mapping tissue proteins with imaging mass spectrometry.',
    'Vertical AI',
    '84 Wood Ln, London W12 0BZ',
    'london',
    51.51590427908501,
    -0.22447633154254965,
    2019,
    null,
    'default',
    'https://www.startupmap.london/companies/micrographia-bio'
  ),
  (
    'strala-ai',
    'Strala',
    'https://www.strala.ai/',
    'Multimodal AI claims platform for intake, routing, fraud detection, and settlements.',
    'Vertical AI',
    '81 Oxford St, London W1D 2EU',
    'london',
    51.51619977216892,
    -0.13355614503608018,
    2019,
    null,
    'default',
    'https://www.startupmap.london/companies/strala-ai'
  ),
  (
    'converge',
    'Converge',
    'https://www.converge.io/',
    'Construction AI platform using sensors and models to monitor concrete curing in real time.',
    'Vertical AI',
    'Level 12 The Shard, 32 London Bridge Street, London SE1 9SG',
    'london',
    51.504535614074115,
    -0.08662058311428714,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/converge'
  ),
  (
    'scope',
    'Scope',
    'https://www.getscope.ai/',
    'AI inspection software for automating field data entry and industrial reporting workflows.',
    'Vertical AI',
    '13 Dolphin Close, London, England, SE28 8PY',
    'london',
    51.5102072,
    0.1244296,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/scope'
  ),
  (
    'metomic',
    'Metomic',
    'https://www.metomic.io/',
    'Data security platform that discovers, classifies, and governs sensitive SaaS data.',
    'Infra',
    'Office One, 1 Coldbath Square, London EC1R 5HL',
    'london',
    51.52389937324244,
    -0.1102866027066226,
    2018,
    null,
    'default',
    'https://www.startupmap.london/companies/metomic'
  ),
  (
    'chattermill',
    'Chattermill',
    'https://chattermill.com/',
    'Customer feedback intelligence platform using AI across text, voice, and survey data.',
    'Vertical AI',
    '68 Hanbury St, London E1 5JL',
    'london',
    51.52013598643889,
    -0.07028461620039053,
    2015,
    null,
    'default',
    'https://www.startupmap.london/companies/chattermill'
  ),
  (
    'genie-ai',
    'Genie AI',
    'https://www.genieai.co/en-gb',
    'Generative legal platform for drafting, reviewing, and refining contracts faster.',
    'Vertical AI',
    '1 Palace Gardens Terrace, Kensington, London',
    'london',
    51.50593722179971,
    -0.19240503154313804,
    2017,
    null,
    'default',
    'https://www.startupmap.london/companies/genie-ai'
  ),
  (
    'limbic',
    'Limbic',
    'https://www.limbic.ai/',
    'Clinical AI platform for automating mental health intake, assessment, and triage.',
    'Vertical AI',
    'Kemp House, 160 City Road, London EC1V 2NX',
    'london',
    51.52721169450224,
    -0.08849989133864958,
    2017,
    null,
    'default',
    'https://www.startupmap.london/companies/limbic'
  ),
  (
    'nplan',
    'nPlan',
    'https://www.nplan.io/',
    'Construction planning AI for forecasting schedule delays and project execution risk.',
    'Vertical AI',
    '68 Hanbury St, London E1 5JL',
    'london',
    51.52014933824909,
    -0.07029534503586149,
    2017,
    null,
    'default',
    'https://www.startupmap.london/companies/nplan'
  ),
  (
    'pactio-technologies',
    'Pactio Technologies',
    'https://www.pactio.io/',
    'Private capital workflow automation company embedding AI into Office tools and reporting.',
    'Vertical AI',
    'Hamilton House, 1 Temple Avenue, London EC4Y 0HA',
    'london',
    51.51142850168047,
    -0.10822338736537948,
    2021,
    null,
    'default',
    'https://www.startupmap.london/companies/pactio-technologies'
  ),
  (
    'cloudnc',
    'CloudNC',
    'https://www.cloudnc.com/',
    'Manufacturing AI company automating CNC programming and toolpath generation.',
    'Vertical AI',
    '1 Norton Folgate, London E1 6DB',
    'london',
    51.520670209343145,
    -0.07864644503584056,
    2015,
    null,
    'default',
    'https://www.startupmap.london/companies/cloudnc'
  ),
  (
    'opply',
    'Opply',
    'https://opply.com/',
    'Ingredient sourcing platform using AI to match food brands with verified suppliers.',
    'Vertical AI',
    '8 Devonshire Square, London EC2M 4TP',
    'london',
    51.517646515990776,
    -0.07917128736502219,
    2021,
    null,
    'default',
    'https://www.startupmap.london/companies/opply'
  ),
  (
    'gensyn',
    'Gensyn',
    'https://www.gensyn.ai/',
    'Decentralized machine learning infrastructure for training models across distributed compute.',
    'Infra',
    'International House, 64 Nile Street, London N1 7SR',
    'london',
    51.529292917504435,
    -0.08836794688377708,
    2020,
    null,
    'default',
    'https://www.startupmap.london/companies/gensyn'
  ),
  (
    'polyai',
    'PolyAI',
    'https://poly.ai/',
    'Enterprise voice agent company automating customer service conversations over phone.',
    'Agents',
    '3 Sheldon Square, London W2 6HY',
    'london',
    51.519770667184176,
    -0.18065098921332687,
    2017,
    null,
    'default',
    'https://www.startupmap.london/companies/polyai'
  ),
  (
    'cleo',
    'Cleo',
    'https://web.meetcleo.com/',
    'Consumer financial assistant using AI for budgeting, coaching, and money management.',
    'Consumer AI',
    '8th Floor, 100 Bishopsgate, London EC2N 4AG',
    'london',
    51.515972196203435,
    -0.08161571620058436,
    2015,
    null,
    'default',
    'https://www.startupmap.london/companies/cleo'
  ),
  (
    'tractable',
    'Tractable',
    'https://tractable.ai/',
    'Computer vision startup automating vehicle and property damage assessment for insurers.',
    'Vertical AI',
    '6 Orsman Rd, London N1 5RA',
    'london',
    51.536947673551474,
    -0.07700017387040733,
    2014,
    null,
    'default',
    'https://www.startupmap.london/companies/tractable'
  ),
  (
    'laddr-ai',
    'Laddr',
    'https://www.theladdr.ai/',
    'AI home search app using swipe-based discovery and recommendations for property seekers.',
    'Consumer AI',
    '34 Worship Street, London EC2A 2AH',
    'london',
    51.522049908881264,
    -0.08494944669155269,
    2024,
    null,
    'default',
    'https://www.startupmap.london/companies/laddr-ai'
  ),
  (
    'upsolve-ai',
    'Upsolve AI',
    'https://upsolve.ai/',
    'Embedded analytics agent for delivering adaptive customer-facing insights in products.',
    'Agents',
    'Shoreditch Exchange, 97-101 Gorsuch Pl, Hackney Rd, London E2 8JF',
    'london',
    51.53026750931674,
    -0.07543124669117957,
    2023,
    null,
    'default',
    'https://www.startupmap.london/companies/upsolve-ai'
  ),
  (
    'dojo-ai',
    'Dojo AI',
    'https://www.getdojo.ai/',
    'Marketing operating system using AI for research, strategy, content, and performance.',
    'Agents',
    '71-75 Shelton Street, Covent Garden, London, United Kingdom, WC2H 9JQ',
    'london',
    51.488780893470064,
    -0.2665145692687139,
    2025,
    null,
    'default',
    'https://find-and-update.company-information.service.gov.uk/company/16434874'
  ),
  (
    'multiply-ai',
    'Multiply AI',
    'https://www.multiply.ai/',
    'Adviser productivity platform using AI to automate financial planning workflows.',
    'Vertical AI',
    '24 Arlington Square, London, England, N1 7DP',
    'london',
    51.53534887339734,
    -0.09259615599766156,
    2016,
    null,
    'default',
    'https://find-and-update.company-information.service.gov.uk/company/10470734'
  ),
  (
    'ben',
    'Ben',
    'https://thanksben.com/',
    'Employee benefits platform using AI to personalize recommendations and automate admin.',
    'Vertical AI',
    '9th Floor 107 Cheapside, London, United Kingdom, EC2V 6DN',
    'london',
    51.52347186061236,
    -0.10452448395089206,
    2019,
    null,
    'default',
    'https://find-and-update.company-information.service.gov.uk/company/12335851'
  ),
  (
    'scarlet',
    'Scarlet',
    'https://www.scarlet.cc/',
    'Regulatory platform focused on software and AI medical device certification in Europe.',
    'Vertical AI',
    '12 New Fetter Lane, London EC4A 1JP',
    'london',
    51.51615484276634,
    -0.10899004503607954,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/scarlet'
  ),
  (
    'fabric',
    'Fabric',
    'https://www.onfabric.io/business',
    'API platform that adds user context signals to search, social, and recommendation systems.',
    'Infra',
    'Flat 1408 Maine Tower 9 Harbour Way, London E14 9DP',
    'london',
    51.49933432496963,
    -0.01994977017569224,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/fabric'
  ),
  (
    'biographica',
    'Biographica',
    'https://graphica.bio/',
    'Graph machine learning company for identifying crop genes from genomic and phenotype data.',
    'Vertical AI',
    '68 Hanbury Street, London E1 5JL',
    'london',
    51.52011431,
    -0.06940646038,
    2022,
    null,
    'default',
    'https://www.startupmap.london/companies/biographica'
  ),
  (
    'stackfix',
    'Stackfix',
    'https://www.stackfix.com/',
    'AI-powered software comparison product for evaluating business tools in seconds.',
    'Consumer AI',
    'WeWork, Aviation House, 125 Kingsway, London WC2B 6NH',
    'london',
    51.51719875308522,
    -0.1207071640566114,
    2023,
    null,
    'default',
    'https://www.startupmap.london/companies/stackfix'
  )
on conflict (city, slug) do update
set
  name = excluded.name,
  website = excluded.website,
  short_description = excluded.short_description,
  category = excluded.category,
  location_label = excluded.location_label,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  founded = excluded.founded,
  logo_url = excluded.logo_url,
  map_sprite = excluded.map_sprite,
  source_url = excluded.source_url;
