insert into public.companies (
  slug,
  name,
  website,
  short_description,
  category,
  location_label,
  city,
  latitude,
  longitude,
  founded,
  logo_url,
  map_sprite,
  source_url
)
values
  (
    'abeja',
    'ABEJA',
    'https://www.abejainc.com',
    'Enterprise AI platform company building data and model systems for mission-critical operations.',
    'Infra',
    '〒108-0073 東京都港区三田1丁目1-14 Bizflex麻布十番2階',
    'tokyo',
    35.655296,
    139.738907,
    2012,
    null,
    'default',
    'https://www.abejainc.com/company'
  ),
  (
    'ai-medical-service',
    'AI Medical Service',
    'https://www.ai-ms.com',
    'Medical AI company developing endoscopy image analysis systems for cancer detection and diagnosis support.',
    'Vertical AI',
    '〒170-0013 東京都豊島区東池袋1丁目18-1 Hareza Tower 11F',
    'tokyo',
    35.732368,
    139.715897,
    2017,
    null,
    'default',
    'https://www.ai-ms.com/company'
  ),
  (
    'apto',
    'APTO',
    'https://apto.co.jp',
    'AI data infrastructure company supporting annotation, evaluation, RLHF, and agent development workflows.',
    'Infra',
    '東京都千代田区岩本町2-4-1 神田岩本町プラザビル504',
    'tokyo',
    35.693642,
    139.775284,
    2020,
    null,
    'default',
    'https://apto.co.jp/en/company/'
  ),
  (
    'araya',
    'Araya',
    'https://www.araya.org',
    'AI and neurotechnology company applying frontier research to enterprise AI and brain-machine interface work.',
    'Core Labs',
    '〒101-0025 東京都千代田区神田佐久間町1-11 産報佐久間ビル6F',
    'tokyo',
    35.697285,
    139.774338,
    2013,
    null,
    'default',
    'https://www.araya.org/en/about/company/'
  ),
  (
    'atama-plus',
    'atama plus',
    'https://atama.plus',
    'Adaptive learning company using AI to personalize study paths and academic support for students.',
    'Vertical AI',
    '東京都文京区後楽2-1-2 住友不動産飯田橋ビル5号館1階',
    'tokyo',
    35.703281,
    139.745758,
    2017,
    null,
    'default',
    'https://corp.atama.plus/company/'
  ),
  (
    'authentic-ai',
    'AuthenticAI',
    'https://authenticai.co.jp',
    'Generative AI company building products and solutions for creative and brand workflows.',
    'Vertical AI',
    '〒107-8526 東京都港区北青山3-5-10 ワールド北青山ビル12階',
    'tokyo',
    35.665634,
    139.712769,
    2024,
    null,
    'default',
    'https://authenticai.co.jp/pages/company'
  ),
  (
    'autify',
    'Autify',
    'https://autify.com',
    'AI-powered software testing platform for generating, running, and managing automated QA workflows.',
    'Devtools',
    '東京都中央区東日本橋2-22-1 Cross-C東日本橋6F',
    'tokyo',
    35.693779,
    139.787186,
    2016,
    null,
    'default',
    'https://autify.com/about'
  ),
  (
    'cogent-labs',
    'Cogent Labs',
    'https://www.cogent.co.jp',
    'Applied AI company delivering OCR, document intelligence, forecasting, and language processing products.',
    'Vertical AI',
    '〒106-0032 東京都港区六本木3-2-1 住友不動産六本木グランドタワー36F',
    'tokyo',
    35.664490,
    139.737473,
    2014,
    null,
    'default',
    'https://www.cogent.co.jp/about/'
  ),
  (
    'elyza',
    'ELYZA',
    'https://elyza.ai',
    'LLM-focused AI company building Japanese language models and enterprise generative AI products.',
    'Core Labs',
    '〒113-0033 東京都文京区本郷3-15-9 SWTビル5・6F',
    'tokyo',
    35.704880,
    139.761948,
    2018,
    null,
    'default',
    'https://elyza.ai/about'
  ),
  (
    'felo',
    'Felo',
    'https://felo.ai',
    'AI search and productivity company building multilingual research, content creation, and agent tools.',
    'Consumer AI',
    '〒100-6510 東京都千代田区丸の内1丁目5-1 新丸の内ビルディング10階',
    'tokyo',
    35.682579,
    139.764313,
    2024,
    null,
    'default',
    'https://official.felo.ai/company/'
  ),
  (
    'japan-ai',
    'JAPAN AI',
    'https://japan-ai.co.jp',
    'Enterprise generative AI company building agent products, apps, and implementation support for business workflows.',
    'Agents',
    '〒163-6006 東京都新宿区西新宿6-8-1 住友不動産新宿オークタワー5/6階',
    'tokyo',
    35.693508,
    139.690369,
    2023,
    null,
    'default',
    'https://japan-ai.co.jp/about/'
  ),
  (
    'legalon-technologies',
    'LegalOn Technologies',
    'https://legalontech.jp',
    'Legal AI company building software for contract review, legal operations, and corporate governance workflows.',
    'Vertical AI',
    '〒150-6219 東京都渋谷区桜丘町1-1 渋谷サクラステージSHIBUYAタワー19F',
    'tokyo',
    35.657352,
    139.701874,
    2017,
    null,
    'default',
    'https://legalontech.jp/company/'
  ),
  (
    'laboro-ai',
    'Laboro.AI',
    'https://laboro.ai',
    'Custom AI development company building machine learning systems for enterprise-specific operational use cases.',
    'Infra',
    '〒104-0061 東京都中央区銀座八丁目11-1',
    'tokyo',
    35.667877,
    139.763000,
    2016,
    null,
    'default',
    'https://laboro.ai/company/profile/'
  ),
  (
    'mntsq',
    'MNTSQ',
    'https://mntsq.co.jp',
    'Contract lifecycle management company applying NLP and AI to legal review and agreement workflows.',
    'Vertical AI',
    '〒104-6004 東京都中央区晴海1丁目8-10 晴海アイランド トリトンスクエア オフィスタワーX棟4階',
    'tokyo',
    35.655556,
    139.781830,
    2018,
    null,
    'default',
    'https://mntsq.co.jp/about'
  ),
  (
    'notta',
    'Notta',
    'https://notta.ai',
    'Voice AI company offering transcription, meeting notes, and conversation intelligence tools.',
    'Consumer AI',
    '〒100-0004 東京都千代田区大手町1-9-2 大手町フィナンシャルシティグランキューブ3階',
    'tokyo',
    35.688286,
    139.765411,
    2022,
    null,
    'default',
    'https://notta.ai/company'
  ),
  (
    'rapyuta-robotics',
    'Rapyuta Robotics',
    'https://www.rapyuta-robotics.com',
    'Cloud robotics company building warehouse automation systems and a robotics platform for connected machines.',
    'Infra',
    '〒135-0043 東京都江東区塩浜2-4-20 6階',
    'tokyo',
    35.664085,
    139.805038,
    2014,
    null,
    'default',
    'https://www.rapyuta-robotics.com/ja/company/'
  ),
  (
    'recursive',
    'Recursive',
    'https://recursiveai.co.jp',
    'AI implementation company developing optimization, sustainability, and enterprise transformation solutions.',
    'Infra',
    'Shibuya S-6 Building 6F, 1-7-1 Shibuya, Shibuya-ku, Tokyo 150-0002, Japan',
    'tokyo',
    35.661030,
    139.706406,
    2020,
    null,
    'default',
    'https://recursiveai.co.jp/about-us'
  ),
  (
    'sakana-ai',
    'Sakana AI',
    'https://sakana.ai',
    'AI research company building frontier foundation model and autonomous research systems from Tokyo.',
    'Core Labs',
    '〒106-0041 東京都港区麻布台1-3-1 麻布台ヒルズ森JPタワー22F',
    'tokyo',
    35.661549,
    139.740921,
    2023,
    null,
    'default',
    'https://sakana.ai/company-info/'
  ),
  (
    'spectee',
    'Spectee',
    'https://spectee.co.jp',
    'Risk intelligence company using AI to detect, analyze, and forecast disasters and crisis events.',
    'Vertical AI',
    '〒102-0076 東京都千代田区五番町12-3 五番町YSビル3階',
    'tokyo',
    35.688980,
    139.733276,
    2011,
    null,
    'default',
    'https://spectee.co.jp/company/'
  ),
  (
    'stockmark',
    'Stockmark',
    'https://stockmark.co.jp',
    'Language AI company helping enterprises extract insight and decisions from large volumes of text data.',
    'Vertical AI',
    '〒107-0062 東京都港区南青山1丁目12-3 LIFORK MINAMI AOYAMA S209',
    'tokyo',
    35.668617,
    139.724838,
    2016,
    null,
    'default',
    'https://stockmark.co.jp/company/'
  ),
  (
    'ubie',
    'Ubie',
    'https://ubie.app',
    'Healthcare AI company building symptom navigation and clinical intake software for patients and providers.',
    'Vertical AI',
    '〒103-0023 東京都中央区日本橋本町3丁目8-4 日本橋ライフサイエンスビルディング4 5F',
    'tokyo',
    35.689568,
    139.776306,
    2017,
    null,
    'default',
    'https://ubie.app/company'
  )
on conflict (city, slug) do update
set
  name = excluded.name,
  website = excluded.website,
  short_description = excluded.short_description,
  category = excluded.category,
  location_label = excluded.location_label,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  founded = excluded.founded,
  logo_url = excluded.logo_url,
  map_sprite = excluded.map_sprite,
  source_url = excluded.source_url;
