insert into public.companies (
  slug,
  name,
  website,
  short_description,
  category,
  location_label,
  city,
  latitude,
  longitude,
  founded,
  logo_url,
  map_sprite,
  source_url
)
values
  (
    'cohere',
    'Cohere',
    'https://cohere.com',
    'Enterprise AI platform building large language models and products for business use.',
    'Core Labs',
    '171 John Street, Suite 200, Toronto, ON M5T 1X3',
    'toronto',
    43.6507434,
    -79.3910699,
    2019,
    null,
    'default',
    'https://cohere.com/ja/privacy'
  ),
  (
    'ada',
    'Ada',
    'https://www.ada.cx',
    'AI agent platform for automating customer service across chat, email, and voice.',
    'Agents',
    '46 Spadina Avenue, Suite 500, Toronto, ON M5V 2H8',
    'toronto',
    43.6446789,
    -79.3949564,
    2016,
    null,
    'default',
    'https://www.ada.cx/legal/website-cookies/'
  ),
  (
    'benchsci',
    'BenchSci',
    'https://www.benchsci.com',
    'AI platform that helps scientists plan experiments and navigate disease biology faster.',
    'Vertical AI',
    '559 College St. Suite 201, Toronto, ON M6G 1A9',
    'toronto',
    43.6551929,
    -79.4123002,
    2015,
    null,
    'default',
    'https://www.benchsci.com/contact'
  ),
  (
    'deep-genomics',
    'Deep Genomics',
    'https://www.deepgenomics.com',
    'AI-powered drug discovery company focused on RNA biology and therapeutic development.',
    'Vertical AI',
    '480 University Avenue, Suite 1300, Toronto, ON M5G 1V2',
    'toronto',
    43.6550868,
    -79.3890234,
    2015,
    null,
    'default',
    'https://www.deepgenomics.com/privacy-policy'
  ),
  (
    'blue-j',
    'Blue J',
    'https://www.bluej.com',
    'Generative AI research platform for tax and legal workflows.',
    'Vertical AI',
    '225 King Street West, Suite 1405, Toronto, ON M5V 3M2',
    'toronto',
    43.6466584,
    -79.3881892,
    2015,
    null,
    'default',
    'https://www.bluej.com/ca/data-processing-agreement'
  ),
  (
    'wisedocs',
    'Wisedocs',
    'https://www.wisedocs.ai',
    'AI platform that turns medical records and claim files into structured review outputs.',
    'Vertical AI',
    '30 Duncan Street #701, Toronto, ON',
    'toronto',
    43.6489309,
    -79.3892882,
    2019,
    null,
    'default',
    'https://www.wisedocs.ai/trust-center'
  ),
  (
    'bluedot',
    'BlueDot',
    'https://bluedot.global',
    'AI-powered infectious disease intelligence for governments, hospitals, and enterprises.',
    'Vertical AI',
    '207 Queens Quay West, Unit 820, Toronto, ON M5J 1A7',
    'toronto',
    43.6383846,
    -79.3804374,
    2013,
    null,
    'default',
    'https://bluedot.global/privacy-policy/'
  ),
  (
    'private-ai',
    'Private AI',
    'https://www.private-ai.com',
    'Privacy-preserving AI company that detects, redacts, and replaces personal data in text and files.',
    'Infra',
    '192 Spadina Avenue, Toronto, ON M5T 2C2',
    'toronto',
    43.6499323,
    -79.3975316,
    2019,
    null,
    'default',
    'https://www.private-ai.com/en/privacy-statement'
  ),
  (
    'nuralogix',
    'NuraLogix',
    'https://www.nuralogix.ai',
    'AI health monitoring platform that analyzes facial blood flow from a short camera scan.',
    'Vertical AI',
    '250 University Avenue, Suite 209, Toronto, ON M5H 3E5',
    'toronto',
    43.6503564,
    -79.3869845,
    2015,
    null,
    'default',
    'https://www.nuralogix.ai/terms-of-use/'
  ),
  (
    'nationgraph',
    'NationGraph',
    'https://www.nationgraph.com',
    'AI-driven sales intelligence platform for public-sector business development.',
    'Agents',
    '180 Dundas St W, Toronto, ON M5G 1Z8',
    'toronto',
    43.6554784,
    -79.3866688,
    2024,
    null,
    'default',
    'https://ca.linkedin.com/company/nationgraph'
  ),
  (
    'superwhisper',
    'Superwhisper',
    'https://superwhisper.com',
    'AI voice to text for macOS, Windows & iOS.',
    'Consumer AI',
    '10 Morrow Ave, Toronto, ON M6R 2J1',
    'toronto',
    43.6525365,
    -79.4472377,
    2024,
    null,
    'default',
    'https://superwhisper.com/careers'
  )
on conflict (slug) do update
set
  name = excluded.name,
  website = excluded.website,
  short_description = excluded.short_description,
  category = excluded.category,
  location_label = excluded.location_label,
  city = excluded.city,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  founded = excluded.founded,
  logo_url = excluded.logo_url,
  map_sprite = excluded.map_sprite,
  source_url = excluded.source_url;
